[options]
admin_passwd = $pbkdf2-sha512$600000$eW/tvXdurRXiXCvFWKv1Xg$Kxs/WF7iTWIZv9iVElchUhmr1NpsvsjMZBUdjN0BOlom8wP1g2PHtuQBUOEsWMOxy0u.DLPJTJofQ2G8Dz3wQA
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
